spring.data.mongodb.uri=mongodb+srv://bertagliafrancesco99_db_user:ouJ9Cjzl01GHTvRk@java.rsgddum.mongodb.net/
spring.data.mongodb.database=txn-demo
spring.threads.virtual.enabled=true
logging.level.com.example=warn
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
